config/routes.rb
Rails.application.routes.draw do
  resources :calls
  resources :clients

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "clients#index"
#root "devise/shared/links"
#session_path
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
 }


=begin
  unauthenticated do
    root :to => 'welcome#index'
  end

  authenticated do
    root :to => 'home#index'
  end
=end
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :client
  belongs_to :Requirement
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: %i[ show edit update destroy ]

  #usuario normal
  before_action  only: %i[:index, :show ] do
    authorize_request (["normal", "ejecutivo", "admin"])
  end
  #usuario ejecutivo
  before_action  only: %i[:new, :edit, :create] do
    authorize_request (["ejecutivo", "admin"])
  end
  #usuario administrador
  before_action  only: %i[:update, :destroy] do
    authorize_request (["admin"])
  end

  # GET /calls or /calls.json
  def index
     @calls = Call.all
     end

  # GET /calls/1 or /calls/1.json
  def show
  end

  # GET /calls/new despliega la vista
  def new
    @call = Call.new
    @
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json encargado de la persistencia
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to call_url(@call), notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to call_url(@call), notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def call_params
      params.require(:call).permit(:reason, :detail, :client_id)
    end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_call.html.erb
<h2> LLamada cliente <%= call.client_id %> <h2>
<hr>
<br>
<div id="<%= dom_id call %>">
<td scope="row">
<%= call.reason %>
</td>
<td>
<%= call.detail %>
</td>
<td>
<%= call.client_id %>
</td>
<td>
<%= call.created_at%>
</td>
</div>

app/views/calls/_form.html.erb
<section>
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reason, style: "display: block" %>
    <%= form.text_field :reason %>
  </div>

  <div>
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_field :detail %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</section>

app/views/calls/edit.html.erb
<h1>Edita</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Mostrar llamada", @call, class:"btn btn-primary" %> |
  <%= link_to "volver", calls_path, class:"btn btn-primary" %>
</div>

app/views/calls/index.html.erb
<p style="color: red">
<%= notice %></p>

<section>
<h1>LLamados</h1>
<div class="btn">
<%= link_to "Nueva llamada", new_call_path, class:"btn btn-info" %>
</div><br/>

<table class=" table">
    <thead>
      <tr>
        <th scope="col">Razon</th>
        <th scope="col">Detalle</th>
        <th scope="col">Clinte ID</th>
        <th scope="col">Fecha de creación</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <hr>
    <tbody>
    <% @calls.each do |call| %>
      <tr>
      <%= render call %>
      <td>
      <div class="btn-group" role="group">
      <%= link_to "mostrar llamada", call, class:"btn btn-info m-1" %>
      <%= link_to "nueva llamada", new_call_path, class:"btn btn-info m-1" %>
      </div>
    <% end %>
    </tbody>
    </table>
    </section>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "regresar a llamdas", calls_path, class:"btn btn-primary"  %>
</div>

app/views/calls/show.html.erb
<p style="color: red">
<%= notice %></p>

<section>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Razon</th>
        <th scope="col">Detalle</th>
        <th scope="col">Clinte ID</th>
        <th scope="col">Fecha de creación</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <hr>

    <tbody>

      <tr>
        <%= render @call %>
      <td>

<div class="btn-group" role="group">
<i class="bi bi-apple"></i>
  <%= link_to "Editar", edit_call_path(@call), class: "btn btn-success me-1" %> 
  <%= link_to "Volver a llamadas", calls_path, class: "btn btn-success me-1" %>
  </div>
  <br>
  <div class="btn-group" role="group">
  <%= link_to "regresar a clietes", clients_path, class: "btn btn-success m-1" %>
  <%= button_to "Eliminar", @call, method: :delete, class: "btn btn-danger m-1" %>
</div>
</table>
</section>