config/routes.rb
Rails.application.routes.draw do
  resources :calls
  resources :clients

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "clients#index"
#root "devise/shared/links"
#session_path
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
 }


=begin
  unauthenticated do
    root :to => 'welcome#index'
  end

  authenticated do
    root :to => 'home#index'
  end
=end
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :calls
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  #usuario normal
  before_action  only: %i[:index, :show ] do
    authorize_request (["normal", "ejecutivo", "admin"])
  end
  #usuario ejecutivo
  before_action  only: %i[:new, :edit, :create] do
    authorize_request (["ejecutivo", "admin"])
  end
  #usuario administrador
  before_action  only: %i[:update, :destroy] do
    authorize_request (["admin"])
  end

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">

  <td scope="row">
    <%= client.id %>
  </td>
  <td>
    <%= client.name %>
  </td>
  <td>
    <%= client.phone %>
  </td>
  <td>
    <%= client.email %>
  </td>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :Telefono, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
<br>
  <div class: "btn btn-success m-1">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar clientes </h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Mostar cliente", @client %> |
  <%= link_to "REGRESAR", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green">
  <%= notice %>
</p>
<section>
<h1>Clientes</h1>
<div class="btn">
<%= link_to "Nuevo Cliente" , new_client_path, class:"btn btn-primary" %>
</div><br/>

  <table class=" table table-primary">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Telefono</th>
        <th scope="col">Email</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>

    <hr>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <%= render client %>
            <td>
              <div class="btn-group" role="group">
                <%= link_to call_path(client.id) do %>
                  <i class="fas fa-mobile-alt fa-lg" style="color: #ff6c52;"></i>
                  <% end %>
                    <%= link_to calls_path do %>
                      <i class="fas fa-file-alt fa-lg m-1" style="color: #fedd06;"></i>
                      <% end %>
                        <%= link_to "Editar" , edit_client_path(client), class: "btn btn-warning m-1 " %>
                          <%= button_to "Eliminar" , client, method: :delete, class: "btn btn-danger m-1" %>
              </div>
            </td>
        </tr>
        <% end %>
    </tbody>

  </table>
  </section>

app/views/clients/new.html.erb
<h1>Nuevo cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Regresar", clients_path, class: "btn btn-success m-1" %>
</div>

app/views/clients/show.html.erb
<p style="color: red">

  <%= notice %>
</p>
<section>
<br>
<h3> Cliente <h3>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre</th>
      <th scope="col">Telefono</th>
      <th scope="col">email</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <hr>
  <tbody>
    <tr>
      <%= render @client %>
        <td>

          <div class="btn-group" role="group">
            <%= link_to "Editar" , edit_client_path(@client), class: "btn btn-success m-1" %>
              <%= button_to "eliminar" , @client, method: :delete , class: "btn btn-danger m-1" %>
              <%= link_to "regresar a clietes", clients_path, class: "btn btn-success m-1" %>
          </div>
          </tr>
          </td>
        </table>
</section>